language: php

php:
  - "7.2.22"
  - "7.1"
  - "7.0"

env:
  - MW=master
  - MW=REL1_34
  - MW=REL1_31

matrix:
  include:
  - php: "7.1"
    env: MW=REL1_27
  - php: "5.5"
    env: MW=REL1_27

services:
  - mysql

before_install:
  - bash ./build/travis/install-mediawiki.sh

install:
  - travis_retry composer install

before_script:
  - bash ./build/travis/run-webserver.sh
  - export ADDWIKI_MW_API='http://localhost:8080/w/api.php'
  - export ADDWIKI_MW_USER='CIUser'
  - export ADDWIKI_MW_PASSWORD='CIPass1234'

script:
  - composer lint
  - composer phpcs
  - composer phpunit-coverage

after_success:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  irc:
    channels:
      - "chat.freenode.net##add"
    on_success: change
    on_failure: always
