FROM mediawiki:1.35.1

RUN apt-get update && \
    apt-get install --yes --no-install-recommends unzip=6.* jq=1.* curl=7.* ca-certificates=202* && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ADD https://raw.githubusercontent.com/wmde/wikibase-docker/262ffef7cc550381309c360e3e92507e85cd8bf6/wikibase/1.35/base/download-extension.sh /
ADD https://raw.githubusercontent.com/wmde/wikibase-docker/262ffef7cc550381309c360e3e92507e85cd8bf6/wikibase/1.35/base/wait-for-it.sh /
ADD build/ /

RUN chmod +x /*.sh

RUN bash /download-extension.sh OAuth;\
tar xzf OAuth.tar.gz;\
mv OAuth /var/www/html/extensions/OAuth

# Hack so we can add a owner only oauth consumer
# https://gist.github.com/addshore/6b148942305b98251cd35203459feb7c
# TODO upstream this...
ADD https://gist.githubusercontent.com/addshore/6b148942305b98251cd35203459feb7c/raw/32efe2ba3b1a271a575eb4cae8f58991082b3af1/gistfile1.txt /var/www/html/extensions/OAuth/maintenance/addwikiAddOauth.php
